# Data source to package the Lambda function
data "archive_file" "lambda_zip" {
  type        = "zip"
  source_dir  = "${path.module}/.."
  output_path = "${path.module}/backend.zip"
  
  excludes = [
    ".git",
    ".pytest_cache",
    "infra",
    "tests",
    "frontend",
    "docs",
    "__pycache__",
    "backend/__pycache__",
    "backend/api/__pycache__",
    "backend/services/__pycache__"
  ]
}

# Lambda Layer for PyMuPDF and dependencies
# This zip is generated by infra/scripts/build_lambda_layer.sh
resource "aws_lambda_layer_version" "pymupdf_layer" {
  filename            = "${path.module}/pymupdf_layer.zip"
  layer_name          = "pymupdf_layer"
  compatible_runtimes = ["python3.9"]
  description         = "Layer containing PyMuPDF, Mangum, and FastAPI"
}

# Lambda Function
resource "aws_lambda_function" "pdf_extractor" {
  filename         = data.archive_file.lambda_zip.output_path
  function_name    = "pdf_extractor_api"
  role             = aws_iam_role.lambda_exec.arn
  handler          = "backend.main.handler"
  source_code_hash = data.archive_file.lambda_zip.output_base64sha256
  runtime          = "python3.9"
  timeout          = 30
  memory_size      = 512

  layers = [aws_lambda_layer_version.pymupdf_layer.arn]

  environment {
    variables = {
      S3_BUCKET_NAME = aws_s3_bucket.pdf_storage.id
    }
  }

  depends_on = [
    aws_iam_role_policy.lambda_s3_policy,
    aws_iam_role_policy_attachment.lambda_logs
  ]
}

# Lambda permission to allow API Gateway invocation
resource "aws_lambda_permission" "apigw_lambda" {
  statement_id  = "AllowExecutionFromAPIGateway"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.pdf_extractor.function_name
  principal     = "apigateway.amazonaws.com"
  
  # source_arn will be linked to the API Gateway created in api_gateway.tf
  source_arn = "${aws_apigatewayv2_api.pdf_api.execution_arn}/*/*"
}
